### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by nachitox** [ctlabvn/Recaptcha#10]
You are assuming that we are using jQuery and code breaks if not.

**Comment by anhtuank7c** [comment]
I do not use jQuery in this plugin.
You can take a look right here: https://github.com/crabstudio/Recaptcha/blob/master/src/Template/Element/recaptcha.ctp

**Comment by nachitox** [comment]
recaptcha's api.js doesn't define $, so `$('.g-recaptcha').each();` is jQuery code (or some other library that uses $)

**Comment by anhtuank7c** [comment]
seem i miss a bit at line 4: https://github.com/crabstudio/Recaptcha/blob/master/src/Template/Element/recaptcha.ctp#L4

**Comment by mirko-pagliai** [comment]
I've the same error:

`ReferenceError: $ is not defined`

I did not understand what I should do.

**Comment by anhtuank7c** [comment]
@mirko-pagliai 
Please use `jquery`

**Comment by mirko-pagliai** [comment]
But it should be written somewhere or even better, to modify that element

**Comment by nachitox** [comment]
the plugin should be vainilla JS. I load jQuery after load, so this breaks my website.

**Comment by anhtuank7c** [comment]
@nachitox @mirko-pagliai 
Please try this one: https://github.com/crabstudio/Recaptcha/releases/tag/2.0.3

**Comment by mirko-pagliai** [comment]
@anhtuank7c thanks

**Comment by nachitox** [comment]
Check my pull request: https://github.com/crabstudio/Recaptcha/pull/12
