### ISSUE TITLE
Mail hide

### ISSUE THREAD

**Issue by mirko-pagliai** [ctlabvn/Recaptcha#13]
I would like to add the "mail hide" feature.

Basically: the helper would have a method to generate a link, the link would open a popup, when the user compiles the recaptcha control, the mail is shown clearly.

This involves:
- add a method to the helper;
- add a controller, a route for the popup and some template files;
- the configuration could no longer be passed directly to the component. For example, it can be set to a file (`config/recaptcha.php`), so that the same configuration works for both the widget and the "mail hide" function.

What do you think about?

**Comment by ADmad** [comment]
That sounds like a pretty specific use case and I personally don't really like the idea of adding what you describe to this plugin. It would be better to make a separate plugin with that feature with this plugin as dependency.

**Comment by mirko-pagliai** [comment]
@ADmad that's what I'm already doing.
Only I was wondering if a single plugin or two separate could be more useful

**Comment by anhtuank7c** [comment]
i have no idea about this issue.
