### ISSUE TITLE
fopen(): SSL operation failed with code 1

### ISSUE THREAD

**Issue by hgnelson83** [ctlabvn/Recaptcha#15]
Hello. I started to get the following errors when I updated CakePHP from 3.3.5 to 3.5.7, and also my hosting site from PHP 5.4.x to PHP7. This happens when I hit submit in the form, with the recaptcha.

`
2017-12-12 12:48:04 Error: [Cake\Core\Exception\Exception] fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
fopen(): Failed to enable crypto
fopen(https://www.google.com/recaptcha/api/siteverify): failed to open stream: operation failed in /home/fe000001/public_html/vendor/cakephp/cakephp/src/Http/Client/Adapter/Stream.php on line 313
`

I am assuming that I am the only one that gets this error, as I see that no one else is getting this error. Maybe the problem relies with a restriction from my web hosting provider.

Any help would be appreciated.

**Comment by ADmad** [comment]
What your distro and openssl client version? You can use `openssl version` on command line to know.

**Comment by hgnelson83** [comment]
Hi. Thanks for your reply.
phpinfo shows the following OpenSSL values:

```
OpenSSL support | enabled
-- | --
OpenSSL Library Version | OpenSSL 1.0.1e-fips 11 Feb 2013
OpenSSL Header Version | OpenSSL 1.0.1e-fips 11 Feb 2013
Openssl default config | /etc/pki/tls/openssl.cnf

```
I don't have access to command line as fas as I know. The host shows "x86_64-redhat-linux-gnu".

**Comment by ADmad** [comment]
That's your problem, upgrade your `openssl` package and issue will be solved.

**Comment by anhtuank7c** [comment]
OMG, you guys still using `CakePHP`, that awesome :)
Thank you @ADmad to answer this issue.

**Comment by vhtellez** [comment]
Get it to work with this quick edit:
in RecaptchaComponent line 29
-'httpClientOptions' => []
+'httpClientOptions' => [ 'ssl_verify_peer' => false ]

Is this a big problem?
