### ISSUE TITLE
Auth Security Exception

### ISSUE THREAD

**Issue by marianodonal** [ctlabvn/Recaptcha#17]
When try to send form i get: Unexpected field 'g-recaptcha-response' in POST data.
The temporary solution is to unlock taht field, but it is not good to include $this->Recaptcha->display() in Form to increase security?

**Comment by ADmad** [comment]
Value for field `g-recaptcha-response` is populated by the recaptcha javascript. Since Security component prevents manipulation of field values through javascript unlocking that field is the only option.

There is no security risk since the repcaptcha respone value is what's actually checked.
