### ISSUE TITLE
Error in production

### ISSUE THREAD

**Issue by vhtellez** [ctlabvn/Recaptcha#18]
this is the error log 

fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
fopen(): Failed to enable crypto
fopen(https://www.google.com/recaptcha/api/siteverify): failed to open stream: operation failed

**Comment by ADmad** [comment]
Duplicate of #15.
