### ISSUE TITLE
CakePHP 4 compatible release.

### ISSUE THREAD

**Issue by ADmad** [ctlabvn/Recaptcha#31]
@anhtuank7c  I had already made a CakePHP 4 compatible branch `cake-4` a while back. We can either merge it to master now or do a `3.0.0-beta` release using that branch itself.

I see you made changes to `master` for 4.x support, that's not necessary and I would suggest to revert (Travis builds are failing because of your changes).

**Comment by anhtuank7c** [comment]
@ADmad Thank you so much

**Comment by ADmad** [comment]
https://github.com/ctlabvn/Recaptcha/releases/tag/3.0.0

**Comment by alanapplyby** [comment]
Is the Cake v4 compatible version available to install via composer yet? 

Coposer:

```
        "php": ">=7.2",
        "cakephp/cakephp": "^4.0",
        "crabstudio/recaptcha": "dev-cake4"
```

crabstudio/recaptcha dev-master requires cakephp/cakephp ^3.5 

Thank you in advance.

**Comment by ADmad** [comment]
@alanapplyby https://github.com/ctlabvn/Recaptcha/issues/34

**Comment by alanapplyby** [comment]
Thanks - readme on the new repo says to use the same: 

composer require crabstudio/recaptcha

I guess I need to chase the owner of the other repository.
