### ISSUE TITLE
Composer package using wrong repo

### ISSUE THREAD

**Issue by ADmad** [ctlabvn/Recaptcha#34]
The composer package https://packagist.org/packages/crabstudio/recaptcha is using the https://github.com/agiletechvn/Recaptcha repo instead of this one.

**Comment by anhtuank7c** [comment]
Yeah. I would like to take a look at this weekend

**Comment by anhtuank7c** [comment]
Dear @ADmad 
I just added you as a maintainer for this package

![image](https://user-images.githubusercontent.com/3163410/100533388-48723880-3236-11eb-8c9c-231d7800d90d.png)

**Comment by anhtuank7c** [comment]
I had pointed to the correct repo now

@ADmad Could you please take a look?

![image](https://user-images.githubusercontent.com/3163410/100533473-6be9b300-3237-11eb-8ea8-3c7f644158e9.png)

**Comment by anhtuank7c** [comment]
![image](https://user-images.githubusercontent.com/3163410/100533558-81131180-3238-11eb-8c35-788b9f4996cb.png)

**Comment by ADmad** [comment]
Thanks.
