### ISSUE TITLE
awesome list

### ISSUE THREAD

**Issue by dereuromark** [ctlabvn/Recaptcha#6]
You chould add yours to https://github.com/FriendsOfCake/awesome-cakephp

**Comment by anhtuank7c** [comment]
@dereuromark 
Where should i add this plugin to `awesome-cakephp`?
Can it be https://github.com/FriendsOfCake/awesome-cakephp/blob/master/README.md#authentication-and-authorization?

**Comment by dereuromark** [comment]
Validation, See the existing captcha plugin

**Comment by anhtuank7c** [comment]
I did it.
Thank you @dereuromark 
https://github.com/FriendsOfCake/awesome-cakephp/pull/259
